# Generated by Django 4.2.7 on 2023-12-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='descriptions',
            new_name='description',
        ),
    ]
