# Generated by Django 4.2.7 on 2023-11-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("value", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("n", "Number"), ("p", "Percent")], max_length=1
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("expire_date", models.DateTimeField()),
            ],
        ),
    ]
