# Generated by Django 4.2.7 on 2023-11-08 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="images/product")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/product"
                    ),
                ),
                ("description", models.TextField(db_index=True)),
                ("price", models.FloatField()),
                ("count", models.IntegerField()),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "attribute",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="products",
                        to="product.attribute",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="discount.discount",
                    ),
                ),
                (
                    "gallery",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="productGallery",
                        to="product.productgallery",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("descriptions", models.TextField()),
                (
                    "score",
                    models.CharField(
                        choices=[
                            ("1", "Very Bad"),
                            ("2", "Bad"),
                            ("3", "Normal"),
                            ("4", "Good"),
                            ("5", "Great"),
                        ],
                        max_length=1,
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("demonstrable", models.BooleanField(default=True)),
                ("recommendable", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="product.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
