# Generated by Django 4.2.7 on 2023-11-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="images/product")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/product"
                    ),
                ),
                ("description", models.TextField(db_index=True)),
                ("price", models.FloatField()),
                ("count", models.IntegerField()),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "attribute",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="product.attribute"
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
