# Generated by Django 4.2.7 on 2023-11-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("discount", "0001_initial"),
        ("shared", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="product_category", to="shared.category"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="discount.discount",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gallery",
            field=models.ManyToManyField(
                blank=True, related_name="product_gallery", to="product.productgallery"
            ),
        ),
    ]
