# Generated by Django 4.2.7 on 2023-11-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_datetime",
            field=models.DateTimeField(
                auto_now_add=True, default="2022-09-20 10:27:21.240752"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
